<a href="https://colab.research.google.com/github/yankit247/Different-Machine-Learning-Models/blob/main/Untitled7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
pd.options.display.float_format = '{:.5f}'.format
pd.options.display.max_rows = None

%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [2]:
train=pd.read_csv('train.csv')

In [3]:
test=pd.read_csv('test.csv')

In [4]:
train=train.fillna(0)
display(train.head())
display(test.head())
train.info()

,ID_LAT_LON_YEAR_WEEK,latitude,longitude,year,week_no,SulphurDioxide_SO2_column_number_density,SulphurDioxide_SO2_column_number_density_amf,SulphurDioxide_SO2_slant_column_number_density,SulphurDioxide_cloud_fraction,SulphurDioxide_sensor_azimuth_angle,...,Cloud_cloud_top_height,Cloud_cloud_base_pressure,Cloud_cloud_base_height,Cloud_cloud_optical_depth,Cloud_surface_albedo,Cloud_sensor_azimuth_angle,Cloud_sensor_zenith_angle,Cloud_solar_azimuth_angle,Cloud_solar_zenith_angle,emission
0,ID_-0.510_29.290_2019_00,-0.51000,29.29000,2019,0,-0.00011,0.60302,-0.00007,0.25567,-98.59389,...,3664.43622,61085.80957,2615.12048,15.56853,0.27229,-12.62899,35.63242,-138.78642,30.75214,3.75099
1,ID_-0.510_29.290_2019_01,-0.51000,29.29000,2019,1,0.00002,0.72821,0.00001,0.13099,16.59286,...,3651.19031,66969.47873,3174.57242,8.69060,0.25683,30.35938,39.55763,-145.18393,27.25178,4.02518
2,ID_-0.510_29.290_2019_02,-0.51000,29.29000,2019,2,0.00051,0.74820,0.00038,0.11002,72.79584,...,4216.98649,60068.89445,3516.28267,21.10341,0.25110,15.37788,30.40182,-142.51954,26.19330,4.23138
3,ID_-0.510_29.290_2019_03,-0.51000,29.29000,2019,3,0.00000,0.00000,0.00000,0.00000,0.00000,...,5228.50774,51064.54734,4180.97332,15.38690,0.26204,-11.29340,24.38036,-132.66583,28.82915,4.30529
4,ID_-0.510_29.290_2019_04,-0.51000,29.29000,2019,4,-0.00008,0.67630,-0.00005,0.12116,4.12127,...,3980.59812,63751.12578,3355.71011,8.11469,0.23585,38.53226,37.39298,-141.50981,22.20461,4.34732

,ID_LAT_LON_YEAR_WEEK,latitude,longitude,year,week_no,SulphurDioxide_SO2_column_number_density,SulphurDioxide_SO2_column_number_density_amf,SulphurDioxide_SO2_slant_column_number_density,SulphurDioxide_cloud_fraction,SulphurDioxide_sensor_azimuth_angle,...,Cloud_cloud_top_pressure,Cloud_cloud_top_height,Cloud_cloud_base_pressure,Cloud_cloud_base_height,Cloud_cloud_optical_depth,Cloud_surface_albedo,Cloud_sensor_azimuth_angle,Cloud_sensor_zenith_angle,Cloud_solar_azimuth_angle,Cloud_solar_zenith_angle
0,ID_-0.510_29.290_2022_00,-0.51000,29.29000,2022,0,NaN,NaN,NaN,NaN,NaN,...,36022.02734,8472.31348,41047.93750,7472.31348,7.93562,0.24077,-100.11379,33.69704,-133.04755,33.77958
1,ID_-0.510_29.290_2022_01,-0.51000,29.29000,2022,1,0.00046,0.69116,0.00032,0.00000,76.23920,...,48539.73724,6476.14732,54915.70858,5476.14716,11.44844,0.29312,-30.51032,42.40259,-138.63282,31.01238
2,ID_-0.510_29.290_2022_02,-0.51000,29.29000,2022,2,0.00016,0.60511,0.00011,0.07987,-42.05534,...,34133.08047,8984.79570,39006.09375,7984.79570,10.75318,0.26713,39.08736,45.93648,-144.78499,26.74336
3,ID_-0.510_29.290_2022_03,-0.51000,29.29000,2022,3,0.00035,0.69692,0.00024,0.20103,72.16957,...,50854.99108,6014.72406,57646.36837,5014.72412,11.76456,0.30468,-24.46513,42.14042,-135.02789,29.60477
4,ID_-0.510_29.290_2022_04,-0.51000,29.29000,2022,4,-0.00032,0.58053,-0.00018,0.20435,76.19086,...,46594.68514,6849.28048,52896.54187,5849.28039,13.06532,0.28422,-12.90785,30.12264,-135.50012,26.27681

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79023 entries, 0 to 79022
Data columns (total 76 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   ID_LAT_LON_YEAR_WEEK                                      79023 non-null  object
 1   latitude                                                  79023 non-null  float64
 2   longitude                                                 79023 non-null  float64
 3   year                                                      79023 non-null  int64
 4   week_no                                                   79023 non-null  int64
 5   SulphurDioxide_SO2_column_number_density                  79023 non-null  float64
 6   SulphurDioxide_SO2_column_number_density_amf              79023 non-null  float64
 7   SulphurDioxide_SO2_slant_column_number_density            79023 non-null  float64
 8   SulphurDioxide_cloud_fraction                             79023 non-null  float64
 9   SulphurDioxide_sensor_azimuth_angle                       79023 non-null  float64
 10  SulphurDioxide_sensor_zenith_angle                        79023 non-null  float64
 11  SulphurDioxide_solar_azimuth_angle                        79023 non-null  float64
 12  SulphurDioxide_solar_zenith_angle                         79023 non-null  float64
 13  SulphurDioxide_SO2_column_number_density_15km             79023 non-null  float64
 14  CarbonMonoxide_CO_column_number_density                   79023 non-null  float64
 15  CarbonMonoxide_H2O_column_number_density                  79023 non-null  float64
 16  CarbonMonoxide_cloud_height                               79023 non-null  float64
 17  CarbonMonoxide_sensor_altitude                            79023 non-null  float64
 18  CarbonMonoxide_sensor_azimuth_angle                       79023 non-null  float64
 19  CarbonMonoxide_sensor_zenith_angle                        79023 non-null  float64
 20  CarbonMonoxide_solar_azimuth_angle                        79023 non-null  float64
 21  CarbonMonoxide_solar_zenith_angle                         79023 non-null  float64
 22  NitrogenDioxide_NO2_column_number_density                 79023 non-null  float64
 23  NitrogenDioxide_tropospheric_NO2_column_number_density    79023 non-null  float64
 24  NitrogenDioxide_stratospheric_NO2_column_number_density   79023 non-null  float64
 25  NitrogenDioxide_NO2_slant_column_number_density           79023 non-null  float64
 26  NitrogenDioxide_tropopause_pressure                       79023 non-null  float64
 27  NitrogenDioxide_absorbing_aerosol_index                   79023 non-null  float64
 28  NitrogenDioxide_cloud_fraction                            79023 non-null  float64
 29  NitrogenDioxide_sensor_altitude                           79023 non-null  float64
 30  NitrogenDioxide_sensor_azimuth_angle                      79023 non-null  float64
 31  NitrogenDioxide_sensor_zenith_angle                       79023 non-null  float64
 32  NitrogenDioxide_solar_azimuth_angle                       79023 non-null  float64
 33  NitrogenDioxide_solar_zenith_angle                        79023 non-null  float64
 34  Formaldehyde_tropospheric_HCHO_column_number_density      79023 non-null  float64
 35  Formaldehyde_tropospheric_HCHO_column_number_density_amf  79023 non-null  float64
 36  Formaldehyde_HCHO_slant_column_number_density             79023 non-null  float64
 37  Formaldehyde_cloud_fraction                               79023 non-null  float64
 38  Formaldehyde_solar_zenith_angle                           79023 non-null  float64
 39  Formaldehyde_solar_azimuth_angle                          79023 non-null  float64
 40  Formaldehyde_sensor_zenith_angle                          79023 non-null  float64
 41  Formaldehyde_sensor_azimuth_angle                         79023 non-null  float64
 42  UvAerosolIndex_absorbing_aerosol_index                    79023 non-null  float64
 43  UvAerosolIndex_sensor_altitude                            79023 non-null  float64
 44  UvAerosolIndex_sensor_azimuth_angle                       79023 non-null  float64
 45  UvAerosolIndex_sensor_zenith_angle                        79023 non-null  float64
 46  UvAerosolIndex_solar_azimuth_angle                        79023 non-null  float64
 47  UvAerosolIndex_solar_zenith_angle                         79023 non-null  float64
 48  Ozone_O3_column_number_density                            79023 non-null  float64
 49  Ozone_O3_column_number_density_amf                        79023 non-null  float64
 50  Ozone_O3_slant_column_number_density                      79023 non-null  float64
 51  Ozone_O3_effective_temperature                            79023 non-null  float64
 52  Ozone_cloud_fraction                                      79023 non-null  float64
 53  Ozone_sensor_azimuth_angle                                79023 non-null  float64
 54  Ozone_sensor_zenith_angle                                 79023 non-null  float64
 55  Ozone_solar_azimuth_angle                                 79023 non-null  float64
 56  Ozone_solar_zenith_angle                                  79023 non-null  float64
 57  UvAerosolLayerHeight_aerosol_height                       79023 non-null  float64
 58  UvAerosolLayerHeight_aerosol_pressure                     79023 non-null  float64
 59  UvAerosolLayerHeight_aerosol_optical_depth                79023 non-null  float64
 60  UvAerosolLayerHeight_sensor_zenith_angle                  79023 non-null  float64
 61  UvAerosolLayerHeight_sensor_azimuth_angle                 79023 non-null  float64
 62  UvAerosolLayerHeight_solar_azimuth_angle                  79023 non-null  float64
 63  UvAerosolLayerHeight_solar_zenith_angle                   79023 non-null  float64
 64  Cloud_cloud_fraction                                      79023 non-null  float64
 65  Cloud_cloud_top_pressure                                  79023 non-null  float64
 66  Cloud_cloud_top_height                                    79023 non-null  float64
 67  Cloud_cloud_base_pressure                                 79023 non-null  float64
 68  Cloud_cloud_base_height                                   79023 non-null  float64
 69  Cloud_cloud_optical_depth                                 79023 non-null  float64
 70  Cloud_surface_albedo                                      79023 non-null  float64
 71  Cloud_sensor_azimuth_angle                                79023 non-null  float64
 72  Cloud_sensor_zenith_angle                                 79023 non-null  float64
 73  Cloud_solar_azimuth_angle                                 79023 non-null  float64
 74  Cloud_solar_zenith_angle                                  79023 non-null  float64
 75  emission                                                  79023 non-null  float64
dtypes: float64(73), int64(2), object(1)
memory usage: 45.8+ MB

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error
from sklearn.svm import SVR

In [6]:
# Create a LabelEncoder object
label_encoder = LabelEncoder()

# Applying level encoding on each column with categorical data
train_ds = train.apply(lambda col: label_encoder.fit_transform(col) if col.dtype == 'object' else col)
test_ds = test.apply(lambda col: label_encoder.fit_transform(col) if col.dtype == 'object' else col)

In [7]:
target = train['emission']
X = train_ds.drop(['ID_LAT_LON_YEAR_WEEK','emission'],axis=1)
y = target.values

In [8]:
# Assuming X contains the features and y contains the labels
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
# Create and train the linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model's performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared Score: {r2}")

Mean Squared Error: 15902.678533477021
R-squared Score: 0.033435204945940766

In [10]:
test=test.fillna(0)
test1=test.drop('ID_LAT_LON_YEAR_WEEK',axis=1)

In [11]:
y_pred=model.predict(X_test)
y_pred

array([ 67.81035356,  83.59601545, 112.92190693, ..., 108.21599209,
       118.16048442,  58.31823172])

In [12]:
model = SVR(kernel='linear')  # You can choose different kernel functions (linear, polynomial, etc.)

# Train the model on the training data
model.fit(X_train, y_train)

# Make predictions on the test data
predicted_values = model.predict(X_test)

# Calculate Mean Squared Error
mse = mean_squared_error(y_test, predicted_values)
print(f"Mean Squared Error: {mse}")

Mean Squared Error: 66894976731.53202

In [13]:
y_pred=model.predict(test1)
y_pred

array([ 288059.97045474, -136335.70203061,  183132.33800845, ...,
       -110156.70007749, -259993.59875913, -339897.59607358])

In [14]:
submission = {
    "ID_LAT_LON_YEAR_WEEK": test['ID_LAT_LON_YEAR_WEEK'].values,
    "emission": y_pred
}
submission

{'ID_LAT_LON_YEAR_WEEK': array(['ID_-0.510_29.290_2022_00', 'ID_-0.510_29.290_2022_01',
        'ID_-0.510_29.290_2022_02', ..., 'ID_-3.299_30.301_2022_46',
        'ID_-3.299_30.301_2022_47', 'ID_-3.299_30.301_2022_48'],
       dtype=object),
 'emission': array([ 288059.97045474, -136335.70203061,  183132.33800845, ...,
        -110156.70007749, -259993.59875913, -339897.59607358])}

In [15]:
# dic to df convert

submission_df = pd.DataFrame(submission)

In [16]:
submission_df.head(5)

       ID_LAT_LON_YEAR_WEEK      emission
0  ID_-0.510_29.290_2022_00  288059.97045
1  ID_-0.510_29.290_2022_01 -136335.70203
2  ID_-0.510_29.290_2022_02  183132.33801
3  ID_-0.510_29.290_2022_03   37223.81066
4  ID_-0.510_29.290_2022_04  -10868.93348

In [17]:
submission_df.to_csv("submission.csv", index=False)

In [18]:
sub=pd.read_csv('submission.csv')